const data = [
  {
    _id: '1',
    name: 'puneeth',
    gender: 'male',
    hometown: 'Hyderabad',
    roomtown: 'Sricity',
    language: 'Telugu',
    occupation: 'Student',
    course: 'CSE',
    alcohol: 'no',
    smoking: 'no',
    culinary: 'can',
    food_preference: 'strictly non veg',
  },
  {
    _id: '2',
    name: 'ramesh',
    gender: 'female',
    hometown: 'salem',
    roomtown: 'Kakinada',
    language: 'Bhojpuri',
    occupation: 'Sweeper',
    course: 'Sweeping course',
    alcohol: 'yes',
    smoking: 'yes',
    culinary: 'cannot',
    food_preference: 'flexible',
  },
  {
    _id: '3',
    name: 'raju_bhai',
    gender: 'male',
    hometown: 'kakinada',
    roomtown: 'Sricity',
    language: 'Telugu',
    occupation: 'Student',
    course: 'CSE',
    alcohol: 'yes',
    smoking: 'yes',
    culinary: 'can',
    food_preference: 'flexible',
  },
  {
    _id: '4',
    name: 'pranav',
    gender: 'male',
    hometown: 'Hyderabad',
    roomtown: 'Sricity',
    language: 'Telugu',
    occupation: 'student',
    course: 'CSE',
    alcohol: 'yes',
    smoking: 'yes',
    culinary: 'sometimes',
    food_preference: 'strictly veg',
  },
  {
    _id: '5',
    name: 'akhilesh',
    gender: 'male',
    hometown: 'Mumbai',
    roomtown: 'Bengaluru',
    language: 'Hindi',
    occupation: 'student',
    course: 'ECE',
    alcohol: 'yes',
    smoking: 'flexible',
    culinary: 'sometimes',
    food_preference: 'strictly veg',
  },
  {
    _id: '6',
    name: 'deepthi',
    gender: 'male',
    hometown: 'Hyderabad',
    roomtown: 'Sricity',
    language: 'Telugu',
    occupation: 'student',
    course: 'CSE',
    alcohol: 'yes',
    smoking: 'flexible',
    culinary: 'sometimes',
    food_preference: 'flexible',
  },
  {
    _id: '7',
    name: 'demo',
    gender: 'female',
    hometown: 'Hyderabad',
    roomtown: 'Sricity',
    language: 'Telugu',
    occupation: 'student',
    course: 'ECE',
    alcohol: 'no',
    smoking: 'no',
    culinary: 'can',
    food_preference: 'strictly non veg',
  },
]
export default data
